local LSM = LibStub("LibSharedMedia-3.0") 

-- ----- 
-- BACKGROUND 
-- ----- 
LSM:Register("background", "arrow_glow", [[Interface\Addons\SharedMedia_MyMedia\background\arrow_glow.tga]]) 
LSM:Register("background", "Caith1", [[Interface\Addons\SharedMedia_MyMedia\background\Caith1.tga]]) 
LSM:Register("background", "Caith2", [[Interface\Addons\SharedMedia_MyMedia\background\Caith2.tga]]) 
LSM:Register("background", "Caith3", [[Interface\Addons\SharedMedia_MyMedia\background\Caith3.tga]]) 
LSM:Register("background", "CaithHalfMoon", [[Interface\Addons\SharedMedia_MyMedia\background\CaithHalfMoon.tga]]) 
LSM:Register("background", "Class1", [[Interface\Addons\SharedMedia_MyMedia\background\Class1.png]]) 
LSM:Register("background", "Class2", [[Interface\Addons\SharedMedia_MyMedia\background\Class2.png]]) 
LSM:Register("background", "Class3", [[Interface\Addons\SharedMedia_MyMedia\background\Class3.png]]) 
LSM:Register("background", "Class4", [[Interface\Addons\SharedMedia_MyMedia\background\Class4.png]]) 
LSM:Register("background", "Druid", [[Interface\Addons\SharedMedia_MyMedia\background\Druid.tga]]) 
LSM:Register("background", "Druid2", [[Interface\Addons\SharedMedia_MyMedia\background\Druid2.png]]) 
LSM:Register("background", "Ecke1", [[Interface\Addons\SharedMedia_MyMedia\background\Ecke1.png]]) 
LSM:Register("background", "Ecke2", [[Interface\Addons\SharedMedia_MyMedia\background\Ecke2.png]]) 
LSM:Register("background", "Hunter", [[Interface\Addons\SharedMedia_MyMedia\background\Hunter.tga]]) 
LSM:Register("background", "Hunter2", [[Interface\Addons\SharedMedia_MyMedia\background\Hunter2.png]]) 
LSM:Register("background", "Mage", [[Interface\Addons\SharedMedia_MyMedia\background\Mage.tga]]) 
LSM:Register("background", "Mage2", [[Interface\Addons\SharedMedia_MyMedia\background\Mage2.png]]) 
LSM:Register("background", "Melli6px", [[Interface\Addons\SharedMedia_MyMedia\background\Melli6px.tga]]) 
LSM:Register("background", "NaowhArrow", [[Interface\Addons\SharedMedia_MyMedia\background\NaowhArrow.tga]]) 
LSM:Register("background", "NaowhArrowLeft", [[Interface\Addons\SharedMedia_MyMedia\background\NaowhArrowLeft.tga]]) 
LSM:Register("background", "NaowhArrowRight", [[Interface\Addons\SharedMedia_MyMedia\background\NaowhArrowRight.tga]]) 
LSM:Register("background", "NaowhGlow", [[Interface\Addons\SharedMedia_MyMedia\background\NaowhGlow.tga]]) 
LSM:Register("background", "overlay_indicator_1", [[Interface\Addons\SharedMedia_MyMedia\background\overlay_indicator_1.blp]]) 
LSM:Register("background", "Paladin", [[Interface\Addons\SharedMedia_MyMedia\background\Paladin.tga]]) 
LSM:Register("background", "Paladin2", [[Interface\Addons\SharedMedia_MyMedia\background\Paladin2.png]]) 
LSM:Register("background", "Priest", [[Interface\Addons\SharedMedia_MyMedia\background\Priest.tga]]) 
LSM:Register("background", "Priest2", [[Interface\Addons\SharedMedia_MyMedia\background\Priest2.png]]) 
LSM:Register("background", "Rogue", [[Interface\Addons\SharedMedia_MyMedia\background\Rogue.tga]]) 
LSM:Register("background", "Rogue2", [[Interface\Addons\SharedMedia_MyMedia\background\Rogue2.png]]) 
LSM:Register("background", "Shaman", [[Interface\Addons\SharedMedia_MyMedia\background\Shaman.png]]) 
LSM:Register("background", "Shaman", [[Interface\Addons\SharedMedia_MyMedia\background\Shaman.tga]]) 
LSM:Register("background", "smooth_backdrop", [[Interface\Addons\SharedMedia_MyMedia\background\smooth_backdrop.tga]]) 
LSM:Register("background", "Warlock", [[Interface\Addons\SharedMedia_MyMedia\background\Warlock.tga]]) 
LSM:Register("background", "Warlock2", [[Interface\Addons\SharedMedia_MyMedia\background\Warlock2.png]]) 
LSM:Register("background", "Warrior", [[Interface\Addons\SharedMedia_MyMedia\background\Warrior.tga]]) 
LSM:Register("background", "Warrior2", [[Interface\Addons\SharedMedia_MyMedia\background\Warrior2.png]]) 
LSM:Register("background", "YuluFiller1", [[Interface\Addons\SharedMedia_MyMedia\background\YuluFiller1.tga]]) 

-- ----- 
--  BORDER 
-- ---- 
LSM:Register("border", "border-glow-overlay", [[Interface\Addons\SharedMedia_MyMedia\border\border-glow-overlay.tga]]) 
LSM:Register("border", "Border_POW", [[Interface\Addons\SharedMedia_MyMedia\border\Border_POW.png]]) 
LSM:Register("border", "bubu01", [[Interface\Addons\SharedMedia_MyMedia\border\bubu01.tga]]) 
LSM:Register("border", "CaithBorder", [[Interface\Addons\SharedMedia_MyMedia\border\CaithBorder.tga]]) 
LSM:Register("border", "Eltreum-Border-1", [[Interface\Addons\SharedMedia_MyMedia\border\Eltreum-Border-1.tga]]) 
LSM:Register("border", "Eltreum-Border-2", [[Interface\Addons\SharedMedia_MyMedia\border\Eltreum-Border-2.tga]]) 
LSM:Register("border", "fer1", [[Interface\Addons\SharedMedia_MyMedia\border\fer1.tga]]) 
LSM:Register("border", "fer10", [[Interface\Addons\SharedMedia_MyMedia\border\fer10.tga]]) 
LSM:Register("border", "fer11", [[Interface\Addons\SharedMedia_MyMedia\border\fer11.tga]]) 
LSM:Register("border", "fer12", [[Interface\Addons\SharedMedia_MyMedia\border\fer12.tga]]) 
LSM:Register("border", "fer13", [[Interface\Addons\SharedMedia_MyMedia\border\fer13.tga]]) 
LSM:Register("border", "fer2", [[Interface\Addons\SharedMedia_MyMedia\border\fer2.tga]]) 
LSM:Register("border", "fer3", [[Interface\Addons\SharedMedia_MyMedia\border\fer3.tga]]) 
LSM:Register("border", "fer4", [[Interface\Addons\SharedMedia_MyMedia\border\fer4.tga]]) 
LSM:Register("border", "fer5", [[Interface\Addons\SharedMedia_MyMedia\border\fer5.tga]]) 
LSM:Register("border", "fer6", [[Interface\Addons\SharedMedia_MyMedia\border\fer6.tga]]) 
LSM:Register("border", "fer7", [[Interface\Addons\SharedMedia_MyMedia\border\fer7.tga]]) 
LSM:Register("border", "fer8", [[Interface\Addons\SharedMedia_MyMedia\border\fer8.tga]]) 
LSM:Register("border", "fer9", [[Interface\Addons\SharedMedia_MyMedia\border\fer9.tga]]) 
LSM:Register("border", "Naowh1", [[Interface\Addons\SharedMedia_MyMedia\border\Naowh1.tga]]) 
LSM:Register("border", "Naowh2", [[Interface\Addons\SharedMedia_MyMedia\border\Naowh2.tga]]) 
LSM:Register("border", "Naowh3", [[Interface\Addons\SharedMedia_MyMedia\border\Naowh3.tga]]) 
LSM:Register("border", "RenaitreBeveled10", [[Interface\Addons\SharedMedia_MyMedia\border\RenaitreBeveled10.tga]]) 
LSM:Register("border", "RenaitreBeveled10x", [[Interface\Addons\SharedMedia_MyMedia\border\RenaitreBeveled10x.tga]]) 
LSM:Register("border", "RenaitreBeveled11", [[Interface\Addons\SharedMedia_MyMedia\border\RenaitreBeveled11.tga]]) 
LSM:Register("border", "RenaitreBeveled11x", [[Interface\Addons\SharedMedia_MyMedia\border\RenaitreBeveled11x.tga]]) 
LSM:Register("border", "RenaitreFade10", [[Interface\Addons\SharedMedia_MyMedia\border\RenaitreFade10.tga]]) 
LSM:Register("border", "RenaitreFade10blk", [[Interface\Addons\SharedMedia_MyMedia\border\RenaitreFade10blk.tga]]) 
LSM:Register("border", "RenaitreFade10x", [[Interface\Addons\SharedMedia_MyMedia\border\RenaitreFade10x.tga]]) 
LSM:Register("border", "RenaitreFade10xblk", [[Interface\Addons\SharedMedia_MyMedia\border\RenaitreFade10xblk.tga]]) 
LSM:Register("border", "RenaitreFade11", [[Interface\Addons\SharedMedia_MyMedia\border\RenaitreFade11.tga]]) 
LSM:Register("border", "RenaitreFade11blk", [[Interface\Addons\SharedMedia_MyMedia\border\RenaitreFade11blk.tga]]) 
LSM:Register("border", "RenaitreFade11x", [[Interface\Addons\SharedMedia_MyMedia\border\RenaitreFade11x.tga]]) 
LSM:Register("border", "RenaitreFade11xblk", [[Interface\Addons\SharedMedia_MyMedia\border\RenaitreFade11xblk.tga]]) 
LSM:Register("border", "RenDefine", [[Interface\Addons\SharedMedia_MyMedia\border\RenDefine.tga]]) 
LSM:Register("border", "RenFade", [[Interface\Addons\SharedMedia_MyMedia\border\RenFade.tga]]) 
LSM:Register("border", "RenFadeB", [[Interface\Addons\SharedMedia_MyMedia\border\RenFadeB.tga]]) 
LSM:Register("border", "roth", [[Interface\Addons\SharedMedia_MyMedia\border\roth.tga]]) 
LSM:Register("border", "rounded-border-small", [[Interface\Addons\SharedMedia_MyMedia\border\rounded-border-small.tga]]) 
LSM:Register("border", "SeerahScalloped", [[Interface\Addons\SharedMedia_MyMedia\border\SeerahScalloped.tga]]) 
LSM:Register("border", "yborder", [[Interface\Addons\SharedMedia_MyMedia\border\yborder.tga]]) 
LSM:Register("border", "yborder2", [[Interface\Addons\SharedMedia_MyMedia\border\yborder2.tga]]) 
LSM:Register("border", "YuluBorderSwitch", [[Interface\Addons\SharedMedia_MyMedia\border\YuluBorderSwitch.tga]]) 
LSM:Register("border", "YuluBorderXI", [[Interface\Addons\SharedMedia_MyMedia\border\YuluBorderXI.tga]]) 

-- -----
--   FONT
-- -----
LSM:Register("font", "1AGBold", [[Interface\Addons\SharedMedia_MyMedia\font\1AGBold.ttf]]) 
LSM:Register("font", "1AGDemi", [[Interface\Addons\SharedMedia_MyMedia\font\1AGDemi.ttf]]) 
LSM:Register("font", "1AGGothMed", [[Interface\Addons\SharedMedia_MyMedia\font\1AGGothMed.ttf]]) 
LSM:Register("font", "1AGMed", [[Interface\Addons\SharedMedia_MyMedia\font\1AGMed.ttf]]) 
LSM:Register("font", "Accidental Presidency", [[Interface\Addons\SharedMedia_MyMedia\font\Accidental Presidency.ttf]]) 
LSM:Register("font", "Cadiz-Black", [[Interface\Addons\SharedMedia_MyMedia\font\Cadiz-Black.ttf]]) 
LSM:Register("font", "Cadiz-Bold", [[Interface\Addons\SharedMedia_MyMedia\font\Cadiz-Bold.ttf]]) 
LSM:Register("font", "Cadiz-ExtraBold", [[Interface\Addons\SharedMedia_MyMedia\font\Cadiz-ExtraBold.ttf]]) 
LSM:Register("font", "Cadiz-ExtraLight", [[Interface\Addons\SharedMedia_MyMedia\font\Cadiz-ExtraLight.ttf]]) 
LSM:Register("font", "Cadiz-Light", [[Interface\Addons\SharedMedia_MyMedia\font\Cadiz-Light.ttf]]) 
LSM:Register("font", "Cadiz-Medium", [[Interface\Addons\SharedMedia_MyMedia\font\Cadiz-Medium.ttf]]) 
LSM:Register("font", "Cadiz-Regular", [[Interface\Addons\SharedMedia_MyMedia\font\Cadiz-Regular.ttf]]) 
LSM:Register("font", "Cadiz-SemiBold", [[Interface\Addons\SharedMedia_MyMedia\font\Cadiz-SemiBold.ttf]]) 
LSM:Register("font", "Cadiz-Thin", [[Interface\Addons\SharedMedia_MyMedia\font\Cadiz-Thin.ttf]]) 
LSM:Register("font", "Cadiz-Ultra", [[Interface\Addons\SharedMedia_MyMedia\font\Cadiz-Ultra.ttf]]) 
LSM:Register("font", "Exo2-ExtraBold", [[Interface\Addons\SharedMedia_MyMedia\font\Exo2-ExtraBold.ttf]]) 
LSM:Register("font", "Future X", [[Interface\Addons\SharedMedia_MyMedia\font\Future X.ttf]]) 
LSM:Register("font", "FutureX-Black", [[Interface\Addons\SharedMedia_MyMedia\font\FutureX-Black.ttf]]) 
LSM:Register("font", "FutureX-Medium", [[Interface\Addons\SharedMedia_MyMedia\font\FutureX-Medium.ttf]]) 
LSM:Register("font", "GothamNarrowBlack", [[Interface\Addons\SharedMedia_MyMedia\font\GothamNarrowBlack.ttf]]) 
LSM:Register("font", "GothamNarrowUltra", [[Interface\Addons\SharedMedia_MyMedia\font\GothamNarrowUltra.ttf]]) 
LSM:Register("font", "GothamXNarrowBlack", [[Interface\Addons\SharedMedia_MyMedia\font\GothamXNarrowBlack.ttf]]) 
LSM:Register("font", "helsinki", [[Interface\Addons\SharedMedia_MyMedia\font\helsinki.ttf]]) 
LSM:Register("font", "impact", [[Interface\Addons\SharedMedia_MyMedia\font\impact.ttf]]) 
LSM:Register("font", "Inter-SemiBold", [[Interface\Addons\SharedMedia_MyMedia\font\Inter-SemiBold.ttf]]) 
LSM:Register("font", "Kanit-Black", [[Interface\Addons\SharedMedia_MyMedia\font\Kanit-Black.ttf]]) 
LSM:Register("font", "Kimberley", [[Interface\Addons\SharedMedia_MyMedia\font\Kimberley.ttf]]) 
LSM:Register("font", "KMT-GothamXN Black", [[Interface\Addons\SharedMedia_MyMedia\font\KMT-GothamXN Black.ttf]]) 
LSM:Register("font", "KMT-GothamXN Ultra", [[Interface\Addons\SharedMedia_MyMedia\font\KMT-GothamXN Ultra.ttf]]) 
LSM:Register("font", "KMT-GothamXNarrow Black", [[Interface\Addons\SharedMedia_MyMedia\font\KMT-GothamXNarrow Black.ttf]]) 
LSM:Register("font", "KMT-GothamXNarrow Ultra", [[Interface\Addons\SharedMedia_MyMedia\font\KMT-GothamXNarrow Ultra.ttf]]) 
LSM:Register("font", "LemonMilk", [[Interface\Addons\SharedMedia_MyMedia\font\LemonMilk.ttf]]) 
LSM:Register("font", "LiberationSans-Regular", [[Interface\Addons\SharedMedia_MyMedia\font\LiberationSans-Regular.ttf]]) 
LSM:Register("font", "LiberationSerif-Regular", [[Interface\Addons\SharedMedia_MyMedia\font\LiberationSerif-Regular.ttf]]) 
LSM:Register("font", "Maebashi", [[Interface\Addons\SharedMedia_MyMedia\font\Maebashi.ttf]]) 
LSM:Register("font", "Mayuta Renshin", [[Interface\Addons\SharedMedia_MyMedia\font\Mayuta Renshin.ttf]]) 
LSM:Register("font", "MBF Prime", [[Interface\Addons\SharedMedia_MyMedia\font\MBF Prime.ttf]]) 
LSM:Register("font", "Metropolis Bold", [[Interface\Addons\SharedMedia_MyMedia\font\Metropolis Bold.ttf]]) 
LSM:Register("font", "Metropolis-Black", [[Interface\Addons\SharedMedia_MyMedia\font\Metropolis-Black.ttf]]) 
LSM:Register("font", "MystikOrbs", [[Interface\Addons\SharedMedia_MyMedia\font\MystikOrbs.ttf]]) 
LSM:Register("font", "Naowh", [[Interface\Addons\SharedMedia_MyMedia\font\Naowh.ttf]]) 
LSM:Register("font", "Narrative", [[Interface\Addons\SharedMedia_MyMedia\font\Narrative.ttf]]) 
LSM:Register("font", "neuropolxrg", [[Interface\Addons\SharedMedia_MyMedia\font\neuropolxrg.ttf]]) 
LSM:Register("font", "NotoSans-Regular", [[Interface\Addons\SharedMedia_MyMedia\font\NotoSans-Regular.ttf]]) 
LSM:Register("font", "NotUI Font Heavy", [[Interface\Addons\SharedMedia_MyMedia\font\NotUI Font Heavy.ttf]]) 
LSM:Register("font", "NotUI Font light", [[Interface\Addons\SharedMedia_MyMedia\font\NotUI Font light.ttf]]) 
LSM:Register("font", "Numbers", [[Interface\Addons\SharedMedia_MyMedia\font\Numbers.ttf]]) 
LSM:Register("font", "OptimusPrinceps", [[Interface\Addons\SharedMedia_MyMedia\font\OptimusPrinceps.ttf]]) 
LSM:Register("font", "Osaka", [[Interface\Addons\SharedMedia_MyMedia\font\Osaka.ttf]]) 
LSM:Register("font", "Pepsi-Cyr-Lat", [[Interface\Addons\SharedMedia_MyMedia\font\Pepsi-Cyr-Lat.ttf]]) 
LSM:Register("font", "Pixel", [[Interface\Addons\SharedMedia_MyMedia\font\Pixel.ttf]]) 
LSM:Register("font", "Pixelify-Bold", [[Interface\Addons\SharedMedia_MyMedia\font\Pixelify-Bold.ttf]]) 
LSM:Register("font", "Pixelify-Medium", [[Interface\Addons\SharedMedia_MyMedia\font\Pixelify-Medium.ttf]]) 
LSM:Register("font", "Pokemon Solid", [[Interface\Addons\SharedMedia_MyMedia\font\Pokemon Solid.ttf]]) 
LSM:Register("font", "Poppins-Black", [[Interface\Addons\SharedMedia_MyMedia\font\Poppins-Black.ttf]]) 
LSM:Register("font", "Poppins-ExtraBold", [[Interface\Addons\SharedMedia_MyMedia\font\Poppins-ExtraBold.ttf]]) 
LSM:Register("font", "Poppins-Regular", [[Interface\Addons\SharedMedia_MyMedia\font\Poppins-Regular.ttf]]) 
LSM:Register("font", "pricedown", [[Interface\Addons\SharedMedia_MyMedia\font\pricedown.ttf]]) 
LSM:Register("font", "Raleway Black", [[Interface\Addons\SharedMedia_MyMedia\font\Raleway Black.ttf]]) 
LSM:Register("font", "Raleway Bold", [[Interface\Addons\SharedMedia_MyMedia\font\Raleway Bold.ttf]]) 
LSM:Register("font", "Reckoner", [[Interface\Addons\SharedMedia_MyMedia\font\Reckoner.ttf]]) 
LSM:Register("font", "Reckoner_Bold", [[Interface\Addons\SharedMedia_MyMedia\font\Reckoner_Bold.ttf]]) 
LSM:Register("font", "Roboto-Bold", [[Interface\Addons\SharedMedia_MyMedia\font\Roboto-Bold.ttf]]) 
LSM:Register("font", "Rock Show Whiplash", [[Interface\Addons\SharedMedia_MyMedia\font\Rock Show Whiplash.ttf]]) 
LSM:Register("font", "SF Diego Sans", [[Interface\Addons\SharedMedia_MyMedia\font\SF Diego Sans.ttf]]) 
LSM:Register("font", "SFX", [[Interface\Addons\SharedMedia_MyMedia\font\SFX.ttf]]) 
LSM:Register("font", "Solange", [[Interface\Addons\SharedMedia_MyMedia\font\Solange.ttf]]) 
LSM:Register("font", "starcine", [[Interface\Addons\SharedMedia_MyMedia\font\starcine.ttf]]) 
LSM:Register("font", "trashco", [[Interface\Addons\SharedMedia_MyMedia\font\trashco.ttf]]) 
LSM:Register("font", "Ubuntu-C", [[Interface\Addons\SharedMedia_MyMedia\font\Ubuntu-C.ttf]]) 
LSM:Register("font", "Ubuntu-L", [[Interface\Addons\SharedMedia_MyMedia\font\Ubuntu-L.ttf]]) 
LSM:Register("font", "Ungai", [[Interface\Addons\SharedMedia_MyMedia\font\Ungai.ttf]]) 
LSM:Register("font", "waltographUI", [[Interface\Addons\SharedMedia_MyMedia\font\waltographUI.ttf]]) 
LSM:Register("font", "WunderUI", [[Interface\Addons\SharedMedia_MyMedia\font\WunderUI.ttf]]) 
LSM:Register("font", "X360", [[Interface\Addons\SharedMedia_MyMedia\font\X360.ttf]]) 
LSM:Register("font", "YanoneKaffeesatz-Regular", [[Interface\Addons\SharedMedia_MyMedia\font\YanoneKaffeesatz-Regular.ttf]]) 
LSM:Register("font", "Zone", [[Interface\Addons\SharedMedia_MyMedia\font\Zone.ttf]]) 

-- -----
--   SOUND
-- -----
LSM:Register("sound", "AmanThulWipe", [[Interface\Addons\SharedMedia_MyMedia\sound\AmanThulWipe.ogg]]) 
LSM:Register("sound", "boomerang", [[Interface\Addons\SharedMedia_MyMedia\sound\boomerang.ogg]]) 
LSM:Register("sound", "bruh", [[Interface\Addons\SharedMedia_MyMedia\sound\bruh.ogg]]) 
LSM:Register("sound", "caution", [[Interface\Addons\SharedMedia_MyMedia\sound\caution.ogg]]) 
LSM:Register("sound", "Character Blast Off Large Chunks of Terrain gibs", [[Interface\Addons\SharedMedia_MyMedia\sound\Character Blast Off Large Chunks of Terrain gibs.ogg]]) 
LSM:Register("sound", "codmissionfailed", [[Interface\Addons\SharedMedia_MyMedia\sound\codmissionfailed.ogg]]) 
LSM:Register("sound", "DispelIllusion", [[Interface\Addons\SharedMedia_MyMedia\sound\DispelIllusion.ogg]]) 
LSM:Register("sound", "DurumuWipe", [[Interface\Addons\SharedMedia_MyMedia\sound\DurumuWipe.ogg]]) 
LSM:Register("sound", "Enhanced - SSJ3 100 - 75 percent Ki AURA ", [[Interface\Addons\SharedMedia_MyMedia\sound\Enhanced - SSJ3 100 - 75 percent Ki AURA .ogg]]) 
LSM:Register("sound", "Interface-sound-10", [[Interface\Addons\SharedMedia_MyMedia\sound\Interface-sound-10.ogg]]) 
LSM:Register("sound", "ionskillissue", [[Interface\Addons\SharedMedia_MyMedia\sound\ionskillissue.ogg]]) 
LSM:Register("sound", "Itjustworks", [[Interface\Addons\SharedMedia_MyMedia\sound\Itjustworks.ogg]]) 
LSM:Register("sound", "mariodeath", [[Interface\Addons\SharedMedia_MyMedia\sound\mariodeath.ogg]]) 
LSM:Register("sound", "metalgear", [[Interface\Addons\SharedMedia_MyMedia\sound\metalgear.ogg]]) 
LSM:Register("sound", "necessary", [[Interface\Addons\SharedMedia_MyMedia\sound\necessary.ogg]]) 
LSM:Register("sound", "ohnonono", [[Interface\Addons\SharedMedia_MyMedia\sound\ohnonono.ogg]]) 
LSM:Register("sound", "oof", [[Interface\Addons\SharedMedia_MyMedia\sound\oof.ogg]]) 
LSM:Register("sound", "QueenAzsharaDissapointing", [[Interface\Addons\SharedMedia_MyMedia\sound\QueenAzsharaDissapointing.ogg]]) 
LSM:Register("sound", "QueenAzsharaWhatAShame", [[Interface\Addons\SharedMedia_MyMedia\sound\QueenAzsharaWhatAShame.ogg]]) 
LSM:Register("sound", "Rules-of-Nature", [[Interface\Addons\SharedMedia_MyMedia\sound\Rules-of-Nature.ogg]]) 
LSM:Register("sound", "shame", [[Interface\Addons\SharedMedia_MyMedia\sound\shame.ogg]]) 
LSM:Register("sound", "wasted", [[Interface\Addons\SharedMedia_MyMedia\sound\wasted.ogg]]) 
LSM:Register("sound", "wasted2", [[Interface\Addons\SharedMedia_MyMedia\sound\wasted2.ogg]]) 
LSM:Register("sound", "WC3Blademaster", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3Blademaster.ogg]]) 
LSM:Register("sound", "WC3BlademasterTwinblade", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3BlademasterTwinblade.ogg]]) 
LSM:Register("sound", "WC3HumanAllyHeroDies", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3HumanAllyHeroDies.ogg]]) 
LSM:Register("sound", "WC3HumanHeroDies", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3HumanHeroDies.ogg]]) 
LSM:Register("sound", "WC3NagaAllyHeroDies", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3NagaAllyHeroDies.ogg]]) 
LSM:Register("sound", "WC3NagaHeroDies", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3NagaHeroDies.ogg]]) 
LSM:Register("sound", "WC3NagaUnitAttack", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3NagaUnitAttack.ogg]]) 
LSM:Register("sound", "WC3NightElfAllyHeroDies", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3NightElfAllyHeroDies.ogg]]) 
LSM:Register("sound", "WC3NightElfHeroDies", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3NightElfHeroDies.ogg]]) 
LSM:Register("sound", "WC3NightElfUnitAttack", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3NightElfUnitAttack.ogg]]) 
LSM:Register("sound", "WC3OrcAllyHeroDies", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3OrcAllyHeroDies.ogg]]) 
LSM:Register("sound", "WC3OrcHeroDies", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3OrcHeroDies.ogg]]) 
LSM:Register("sound", "WC3RokhanBeHappy", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3RokhanBeHappy.ogg]]) 
LSM:Register("sound", "WC3RokhanFeel", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3RokhanFeel.ogg]]) 
LSM:Register("sound", "WC3RokhanHear", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3RokhanHear.ogg]]) 
LSM:Register("sound", "WC3RokhanTazdingo", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3RokhanTazdingo.ogg]]) 
LSM:Register("sound", "WC3UndeadAllyHeroDies", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3UndeadAllyHeroDies.ogg]]) 
LSM:Register("sound", "WC3UndeadHeroDies", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3UndeadHeroDies.ogg]]) 
LSM:Register("sound", "WC3UndeadUnderAttack", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3UndeadUnderAttack.ogg]]) 
LSM:Register("sound", "WC3UndeadUnitAttack", [[Interface\Addons\SharedMedia_MyMedia\sound\WC3UndeadUnitAttack.ogg]]) 
LSM:Register("sound", "Weretoolate", [[Interface\Addons\SharedMedia_MyMedia\sound\Weretoolate.ogg]]) 
LSM:Register("sound", "WillSmith-Ahaha", [[Interface\Addons\SharedMedia_MyMedia\sound\WillSmith-Ahaha.ogg]]) 
LSM:Register("sound", "WillSmith-Rewind-Long", [[Interface\Addons\SharedMedia_MyMedia\sound\WillSmith-Rewind-Long.ogg]]) 
LSM:Register("sound", "WillSmith-Thats-hot", [[Interface\Addons\SharedMedia_MyMedia\sound\WillSmith-Thats-hot.ogg]]) 
LSM:Register("sound", "Withered", [[Interface\Addons\SharedMedia_MyMedia\sound\Withered.ogg]]) 
LSM:Register("sound", "wow", [[Interface\Addons\SharedMedia_MyMedia\sound\wow.ogg]]) 
LSM:Register("sound", "xera", [[Interface\Addons\SharedMedia_MyMedia\sound\xera.ogg]]) 
LSM:Register("sound", "You_Died", [[Interface\Addons\SharedMedia_MyMedia\sound\You_Died.ogg]]) 

-- -----
--   STATUSBAR
-- -----
LSM:Register("statusbar", "Eltreum-Blank", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Eltreum-Blank.tga]]) 
